version: "3.8"
services:
  apache:
    build:
      context: .
    volumes:
      - ./app:/usr/local/apache2/htdocs
    ports:
      - 8000:80
    image: my-apache-wasm
    container_name: my-apache-wasm
